### ISSUE TITLE
ok to use cspack?

### ISSUE THREAD

**Issue by ghost** [andrerod/cspack#12]
@andrerod Excited to see this cspack implementation.  Is it cool to test and use?   From reading the tests it looks pretty straightforward:
1.  Clone into a node_modules folder
2.  Require it
3.  New up the CsPack object and fire the execute method

``` javascript
 var csPack = new CsPack( {
     inputDirectory:  process.cwd()
  ,  serviceDefinitionFile:  process.cwd() + '/ServiceDefinition.csdef'
  ,  outputfile:  process.cwd() + '/myPkg.cspkg' 
  })

  csPack.execute(  function( err ) {
    cb( err )
  })
```

I assume from there I can use azure-sdk-for-node to upload the package to blob storage, create a hosted service and then create a deployment where I point to the uploaded package?

**Comment by ghost** [comment]
@andrerod sorry... did this cspack make it into something under https://github.com/WindowsAzure?

**Comment by andrerod** [comment]
@gscott not yet. Priorities, priorities ... What scenario would you like to support ?

**Comment by Andrewpk** [comment]
@andrerod I'd love to be able to deploy a cloud service from OS X or Linux

**Comment by matias-sandell** [comment]
+1

**Comment by ghost** [comment]
Closing, everyone has rightly moved on.   

I will say that I was intrigued by [Service Fabric](https://azure.microsoft.com/en-us/services/service-fabric/) thinking, ah, with this next-gen approach, surely there will be a xplat packaging solution -- and then 💥 ! [another Windows executable!](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-deploy-existing-app/#process-of-packaging-an-existing-app)
